run_name: "YYMMDD"
output_dir: /data/projects/myProject/seqRunId
repseqs_run_name: "YYMMDD"
repseqs_qza_file: null
table_qza_file: null
sample_metadata_file: /data/projects/myProject/seqRunId/00_metadata.tsv
database_name: pr2_v5.0.0_SSU_18S-V9-2501_uniq-classifier
refseqs_file: null
taxa_file: null
classify_method: naive-bayes
taxa_ranks: kingdom,phylum,class,order,family,genus,species
collapse_taxalevel: 7
classify_threads: 8
pretrained_classifier: /data/databases/qiime2/18S-PR2/pr2-5.0.0/ssu18sv9-pr2-250122/pr2_v5.0.0_SSU_18S-V9-2501_uniq-classifier.qza
skl_confidence: 0.7
perc_identity: 0.8
query_cov: 0.8
min_consensus: 0.51
bowtie_database: null
confidence_thres: 0.8
classify_params: --verbose
