run_name: "YYMMDD"
output_dir: /data/projects/myProject/seqRunId
raw_fastq_path: null
trimmed_fastq_path: null
sample_manifest_file: /data/projects/myProject/manifests/seqRunId_manifest_pe.tsv
preexisting_fastq_qza: null
paired_end: true
to_trim: true
to_merge: false
assay_name: Eukarya-18S-V9-AmaralZettler
fwd_primer: GTACACACCGCCCGTC
rev_primer: TGATCCTTCTGCAGGTTCACCTAC
discard_untrimmed: false
minimum_length: 50
maxdiffs: 20
merge_stagger: --p-allowmergestagger
trimming_threads: 8
seq_quality_cutoff: 0.85
