run_name: "YYMMDD"
output_dir: /data/projects/myProject/seqRunId
qaqc_run_name: null
fastq_qza_file: null
sample_metadata_file: /data/projects/myProject/metadata/seqRunId_metadata.tsv
plot_diversity: true
alpha_max_depth: 5000
core_sampling_depth: 5000
asv_method: dada2pe
asv_threads: 8
dada2_trunc_len_f: 100
dada2pe_trunc_len_r: 100
dada2_trim_left_f: 0
dada2pe_trim_left_r: 0
dada2_max_ee_f: 2
dada2pe_max_ee_r: 2
dada2_trunc_q: 2
dada2_pooling_method: pseudo
dada2_chimera_method: consensus
dada2_min_fold_parent_over_abundance: 1
dada2_n_reads_learn: 1000000
dada2_hashed_feature_ids: --p-hashed-feature-ids
deblur_trim_length: 150
deblur_trim_left: 0
deblur_mean_error: 0.005
deblur_min_reads: 2
deblur_min_size: 2
deblur_indel_max: 3
reference_seqs: null
to_filter: false
samples_to_filter: null
min_sample_reads: 0
repseq_min_length: 0
repseq_max_length: 0
repseq_min_abundance: 0
repseq_min_prevalence: 0
repseq_min_frequency: 0
repseq_min_samples: 0
